#!/bin/python3
#varraible 
print("============================")
print("Develop by sophavin ly 2023")
print("============================\n")
print("Varriable in Python ")
name = "ly sophavin" #String 
age = 18 #integer 
height  = 3.2 #float - has Decimal 

print("String " + name)
print("Integer " + str(age))
print("Float "+ str(height))

print("=================================================")
print("Math in python \n")
print("add  50 + 50: " + str (50 + 50)) #add
print("subtract 50 - 50: " + str(50 - 50)) #subtract
print("multiply 50 * 50: " + str (50 * 50)) #multiply
print("divide 50 / 50: " + str(50 / 50)) #divide
print("PEMDAS 50 + 50 - 50 * 50 / 50: "+ str(50 + 50 - 50 * 50 / 50)) #PEMDAS 
print("exponets 50 ** 2: "+ str(50 ** 2)) #exponets
print("modulo - taek what is left over 50 % 6: "+ str (50 % 6))
print("division with remainder(or float )  50 / 6: " +str(50 / 6) )
print("no remainder 50 // 6: "+ str (50 // 6)) # no rimainder 
print("=================================================")
print('\n')
print("String Text in python ")
word = "I love you "
print("word given = " + word)
print("This is upper case word : " + word.upper()) #upper case
print("This is Lower case word : " + word.lower()) # lower case 
print("This is title case word : " + word.title()) # title case 
print("This is Character we count")
print(len(word)) #count character  
print("=================================================\n")
print("=================================================")
print("Function")
print("we use keyword def is the keyword for defining a function\n")

def show():
    name = "Sophavin"
    age = 18
    print("My name is " + name + " and I'm " + str(age) + " years olds.")    

show()
# we add number we add paremeter
def add_one_hundred(num):
    print(num + 100)
 
print("we use function add_one_hundred + 100")
add_one_hundred(100)    

print("Function add")
def add(x,y):
      print(x + y)
      
print("add(7,7)")
add(7,7)

print("Function multiply")
def multiply(x,y):
    return x * y
    
print("we use function multiply(7,7) ")
multiply(7,7)
print(multiply(7,7))

def sqare_root(x):
         print(x ** .5)
         
print("Function sqare_root")       
sqare_root(64)

def nl(): # new line
   print('\n')

print("=================================================")
nl()

print("=================================================")
print("BOOLEAN EXPRESSIONS {TRUE OR FALSE}")

bool1 = True
bool2 = 3*3 == 9
bool3 = False 
bool4 = 3*3 != 9
bool5 = "True"
print("bool1 = True bool2 = 3*3 == 9 bool3 = False  bool4 = 3*3 != 9 bool5 = True \n")
print("we print conditions as boolean ")
print(bool1,bool2,bool3,bool4)
nl()
print("We can you varrieble of boolean by using keyword type")
print(type(bool1))
print(type(bool2))
print(type(bool5))
print("=================================================")

print("=================================================")
print("Relational and boolean operation") 
print("=================================================")
greater_than = 7 > 5 
less_than = 5 < 7 
greater_than_equal_to = 7 >= 7 
less_than_equal_to = 7 <= 7

test_and = (7 > 5) and (5 < 7) # True
test_and2 = (7 > 5) and (5 >7) #False
test_or = (7 > 5) or (5 < 7) #True 
test_or2 = (7 > 5) or ( 5 > 7) #True 
test_not = not True #false
print("=================================================")
nl()
print("CONDITION STSTAMENT if / else \n")
print("================================")
def Drink(money):
      if money >= 2: 
            return "you got yourself a Drink!"
      else: 
            return "NO Drink for You bro!"
            
            
print("if you have 3$")
print(Drink(3))
print("=============================")
print("if you have 1$")
print(Drink(1))   
print("=============================")
nl()

def alcohol(age, money):
              if(age >= 21) and (money >= 5):
                 return "We're getting a Drink!"
              elif(age >= 21 ) and (money < 5):
                 return "Come back with more Money."
              elif(age < 21) and (money >= 5):
                  return "Nice,try kid!" 
              else:
                  return "you're too young and too poor."

print("-----------\tCondition can Drink alcohol\t--------------")                 
print("====================================================")
print("if you greater than 25 and have money 5$")  
print(alcohol(21,5))
print("====================================================")
print("if you greater than 25 and you have money 4$")
print(alcohol(21,4))
print("====================================================")
print("if you smalless than 25 and you have money 5$")
print(alcohol(20,5))
print("====================================================")
print("if you 20 years olds and you have money 4$")
print(alcohol(20,4))
print("====================================================")

nl()
print("====================================================")
print("-------------------\tList in python\t---------------")
print("====================================================")
#list have bracket [] 
movies = ["Spiderman","Avanger End game","Goodnight mommy","John wich4"]
print("\t\tList favorite movies\n")
print("===================================================")
print("\t\tThe list my fav movies is \n" + str(movies)+ '\n')
print("===================================================")

print("The first movie is \n" + ">> " + str(movies[0]) + '\n') # the list start from index 0
print("The Seconds movie is \n" + ">> " + str(movies[1]) + '\n') 
print("The third movie is \n" + ">> " + str(movies[2]) + '\n')
print("The fourt movie is \n" + ">> " + str(movies[3]))
print("\n")
movies.append("IT")
print("iteam count "+ str(len(movies)))
print("We add moive using append keyword \n")
print(movies)
print("\nWe can insert movie To what possition you want by using keyword insert\n")
movies.insert(2,"SuperMan")
print(movies)

print("\nWe can remove iteam in list by using keyword pop in the last of list ")
movies.pop()
print(movies)

nl()
print("==============")
print("Loop in python\n for loop \n while")
print("==============\n")
print("\tfor loop")
print("\t--------\n")
print("--------------------------------")
print("This is Energy Drink in Cambodia")
print("--------------------------------")
fav = ["Coca Cola","Pepsi","Sting","Monster","Caraboa","RedBulll"]
for x in fav:
     print(x)
    
nl()
print("\tWhile Loop")
print("\t----------")
 
 
num = 1

while num < 10:
        print(num)
        num += 1 

print("\n\t Advance String\n")
print("\t------------------\n")
print("I declare my name As Sophavin\nI can print my name as Index of letter\n")

my_name = "Sophavin"
print("my print my first letter of my name ")
print("= " + my_name[0] +"\n")
       
print("and i print my last letter of my name ")
print("= " + my_name[-1])


sentence = "This is Sentence"
print("i print word This beacause word have 4 index\n")
print(sentence[:4])

print("\n we Can use keyword split() in python will check space\n")
print(sentence.split())

sentence_split = sentence.split()
sentence_join = ' '.join(sentence.split()) 
print(sentence_join)

quote = "HE said,'Give me all your money'"
print(quote)
quote = "He said, \"give me all your money\""
print(quote)

too_much_space = "                        hello    "
print(too_much_space.strip())

print("A" in "Apple") #True
print("a" in "Apple") #False

letter = "A"
word = "Apple"
print(letter.lower() in word.lower()) #iproved 

movie = "Legend of chousen"
print("My favorite movie is {}.".format(movie))
print("My faveorite movie is %s." % movie)
print(f"My favorite movie is {movie}.")


nl()
print("\t\tDicitionaries")
print("\t\t-------------")
print("\tkey/value pairs {} [] () ")

drinks = {"While Russain": 7, "Old Fashined": 10, "Lemon Drop": 8}
print(drinks)

employess = {"Finace": ["sophavin"],"IT":["Syber security"]}                           
print(employess)

employess['legal'] = ["Mr. Robot"]
print(employess)

drinks['White Cambodia'] = 8
print(drinks)
print("\n")
print(drinks.get("White Cambodia"))

employess.update({"IT":
[
"Cyber Security",
"Webs Developer", 
"Mobile Development", 
"Networking", 
"Data Scient", 
"Desinger", 
"FrontEnd ", 
"BackEnd"]})
print(employess)
print("=======================================")




